CREATE DATABASE Matcha;

use Matcha;

-- CREATE TABLE test(`id` int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL, `test` VARCHAR(233) NOT NULL);

CREATE TABLE IF NOT EXISTS users(`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, `email` VARCHAR(255) NOT NULL, `userName` VARCHAR(255) NOT NULL, `firstName` VARCHAR(255) NOT NULL, `lastName` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NOT NULL, `vkey` VARCHAR(255) NOT NULL, `verify` int(11) NOT NULL DEFAULT 0);

-- INSERT INTO `test` (`id`, `test`) VALUES (NULL, 'w');